# -*- coding: utf-8 -*-
"""Google_search.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3aOPyjLapxhIkg8bicfGzwEKc37M7d7
"""

import requests
import bs4


text= "spacex"
url = 'https://google.com/search?q=' + text


request_result=requests.get( url )


soup = bs4.BeautifulSoup(request_result.text,
						"html.parser")
print(soup)

